name: itschessnotcheckers
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py310h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.10=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - flatbuffers==23.3.3
      - gast==0.4.0
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.53.0
      - h5py==3.8.0
      - idna==3.4
      - jax==0.4.8
      - keras==2.12.0
      - libclang==16.0.0
      - llvmlite==0.39.1
      - markdown==3.4.3
      - markupsafe==2.1.2
      - ml-dtypes==0.1.0
      - numba==0.56.4
      - numpy==1.23.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==1.4.3
      - protobuf==4.22.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.1.2
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - six==1.16.0
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.2.0
      - tqdm==4.65.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
      - werkzeug==2.2.3
      - wrapt==1.14.1
